/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'BaseBadge.component': typeof import('./components/base-badge/base-badge.component.vue')['default']
    BaseButton: typeof import('./components/base-button/base-button.vue')['default']
    'BaseButton.component': typeof import('./components/base-button/base-button.component.vue')['default']
    BaseCard: typeof import('./components/base-card/base-card.vue')['default']
    'BaseCard.component': typeof import('./components/base-card/base-card.component.vue')['default']
    CircularProgress: typeof import('./components/circular-progress/circular-progress.vue')['default']
    'CircularProgress.component': typeof import('./components/circular-progress/circular-progress.component.vue')['default']
    IconLoader: typeof import('./components/icon-loader/icon-loader.vue')['default']
    'IconLoader.component': typeof import('./components/icon-loader/icon-loader.component.vue')['default']
    ImageLoader: typeof import('./components/image-loader/image-loader.vue')['default']
    'ImageLoader.component': typeof import('./components/image-loader/image-loader.component.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./components/the-header/the-header.vue')['default']
    'TheHeader.component': typeof import('./components/the-header/the-header.component.vue')['default']
    ThemeToggler: typeof import('./components/theme-toggler/theme-toggler.vue')['default']
    'ThemeToggler.component': typeof import('./components/theme-toggler/theme-toggler.component.vue')['default']
    'Toast.component': typeof import('./components/toast/toast.component.vue')['default']
    ToastManager: typeof import('./components/toast-manager/toast-manager.vue')['default']
    'ToastManager.component': typeof import('./components/toast-manager/toast-manager.component.vue')['default']
    ToastMessage: typeof import('./components/toast/toast-message.vue')['default']
    WeatherSidebar: typeof import('./components/weather-sidebar/weather-sidebar.vue')['default']
    'WeatherSidebar.component': typeof import('./components/weather-sidebar/weather-sidebar.component.vue')['default']
  }
}
