/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseBadge: typeof import('./components/base-badge/base-badge.vue')['default']
    BaseButton: typeof import('./components/base-button/base-button.vue')['default']
    BaseCard: typeof import('./components/base-card/base-card.vue')['default']
    CircularProgress: typeof import('./components/circular-progress/circular-progress.vue')['default']
    IconLoader: typeof import('./components/icon-loader/icon-loader.vue')['default']
    ImageLoader: typeof import('./components/image-loader/image-loader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./components/the-header/the-header.vue')['default']
    ThemeToggler: typeof import('./components/theme-toggler/theme-toggler.vue')['default']
    Toast: typeof import('./components/toast/toast.vue')['default']
    ToastManager: typeof import('./components/toast-manager/toast-manager.vue')['default']
    WeatherSidebar: typeof import('./components/weather-sidebar/weather-sidebar.vue')['default']
  }
}
